<?php

namespace PCextreme\Cloudstack\Console;

use PCextreme\Cloudstack\Client;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;

class ApiListCommand extends Command
{
    /**
     * Configures the current command.
     *
     * @return void
     */
    protected function configure()
    {
        $this->setName('api:list')
            ->setDescription('Generate API list cache.')
            ->setHelp("This will generate the API list cache file usign the 'listApis' command.");
    }

    /**
     * Executes the current command.
     *
     * @param  InputInterface  $input
     * @param  OutputInterface $output
     * @return void
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $urlApi    = $this->askUrlApi($input, $output);
        $apiKey    = $this->askApiKey($input, $output);
        $secretKey = $this->askSecretKey($input, $output);

        $output->writeLn('');
        $output->writeLn("<info>Processing API list. Please Wait...</info>");

        $client = new Client([
            'urlApi'    => $urlApi,
            'apiKey'    => $apiKey,
            'secretKey' => $secretKey,
        ]);

        $command = 'listApis';
        $method  = $client->getCommandMethod($command);
        $url     = $client->getCommandUrl($command, []);
        $request = $client->getRequest($method, $url, []);

        $list = $client->getResponse($request);
        $this->processList($output, $list);
    }

    /**
     * Ask for URL API.
     *
     * @param  InputInterface  $input
     * @param  OutputInterface $output
     * @return string
     */
    protected function askUrlApi(InputInterface $input, OutputInterface $output)
    {
        $question = new Question(
            'Enter target API url [default: https://api.auroracompute.eu/ams]: ',
            'https://api.auroracompute.eu/ams'
        );

        return $this->getHelper('question')->ask($input, $output, $question);
    }

    /**
     * Ask for API key.
     *
     * @param  InputInterface  $input
     * @param  OutputInterface $output
     * @return string
     */
    protected function askApiKey(InputInterface $input, OutputInterface $output)
    {
        $question = (new Question('Enter API key: '))
            ->setValidator(function ($answer) {
                if (is_null($answer)) {
                    throw new \InvalidArgumentException("API key can't be null.");
                }

                return $answer;
            })
            ->setMaxAttempts(2);

        return $this->getHelper('question')->ask($input, $output, $question);
    }

    /**
     * Ask for secret key.
     *
     * @param  InputInterface  $input
     * @param  OutputInterface $output
     * @return string
     */
    protected function askSecretKey(InputInterface $input, OutputInterface $output)
    {
        $question = (new Question('Enter secret key: '))
            ->setValidator(function ($answer) {
                if (is_null($answer)) {
                    throw new \InvalidArgumentException("Secret key can't be null.");
                }

                return $answer;
            })
            ->setMaxAttempts(2);

        return $this->getHelper('question')->ask($input, $output, $question);
    }

    /**
     * Dump cache file of APIs list.
     *
     * @param  OutputInterface $output
     * @param  array           $list
     * @return void
     */
    protected function processList(OutputInterface $output, array $list = [])
    {
        if (empty($list)) {
            throw new \RuntimeException("API list is empty.");
        }

        $progress = new ProgressBar($output, $list['listapisresponse']['count']);
        $progress->start();

        $listFile = "<?php\n\n";
        $listFile .= "// api_list.php @generated by api:list command\n\n";
        $listFile .= "return array(\n";

        foreach ($list['listapisresponse']['api'] as $api) {
            $name        = $api['name'];
            $description = addslashes($api['description']);
            $isAsync     = $api['isasync'];

            $listFile .= "    '$name' => array(\n";
            $listFile .= "        'description' => '$description',\n";
            $listFile .= "        'isasync'     => " . ($isAsync ? "true" : "false") . ",\n";
            $listFile .= "        'params'      => array(\n";

            foreach ($api['params'] as $param) {
                $paramName        = $param['name'];
                $paramDescription = addslashes($param['description']);
                $paramType        = $param['type'];
                $paramRequired    = $param['required'];

                $listFile .= "            '$paramName' => array(\n";
                $listFile .= "                'description' => '$paramDescription',\n";
                $listFile .= "                'type'        => '$paramType',\n";
                $listFile .= "                'required'    => " . ($paramRequired ? "true" : "false") . ",\n";
                $listFile .= "            ),\n";
            }

            $listFile .= "        ),\n";
            $listFile .= "    ),\n";

            $progress->advance();
        }

        $listFile .= ");\n";

        file_put_contents(__DIR__ . '/../../cache/api_list.php', $listFile);

        $progress->finish();
    }
}
